pub fn generate(module_stem: &str) -> (String, String) {
    let cmake_lists = generate_cmakelists(module_stem);
    let ea_compiler_cmake = EA_COMPILER_CMAKE.to_string();
    (cmake_lists, ea_compiler_cmake)
}

fn generate_cmakelists(stem: &str) -> String {
    let mut out = String::new();
    out.push_str("# CMakeLists.txt — generated by ea bind\n");
    out.push_str("cmake_minimum_required(VERSION 3.16)\n");
    out.push_str(&format!("project({stem} C)\n\n"));
    out.push_str("include(EaCompiler.cmake)\n\n");
    out.push_str(&format!("add_ea_kernel({stem} {stem}.ea)\n\n"));
    out.push_str(&format!("add_executable(app main.c)\n"));
    out.push_str(&format!("target_link_libraries(app {stem} m)\n"));
    out
}

const EA_COMPILER_CMAKE: &str = r#"# EaCompiler.cmake — CMake integration for the Eä SIMD compiler
#
# Usage:
#   include(cmake/EaCompiler.cmake)
#   add_ea_kernel(<target> <source.ea>)
#   target_link_libraries(myapp <target>)
#
# This creates an imported static library target from the .ea source.
# The generated .h header is exposed via the target's include directory.

find_program(EA_COMPILER ea REQUIRED)

function(add_ea_kernel target source)
    # Resolve to absolute path
    get_filename_component(source_abs "${source}" ABSOLUTE)
    get_filename_component(stem "${source}" NAME_WE)

    set(obj_file "${CMAKE_CURRENT_BINARY_DIR}/${stem}.o")
    set(header_file "${CMAKE_CURRENT_BINARY_DIR}/${stem}.h")

    # Compile .ea → .o + .h
    add_custom_command(
        OUTPUT "${obj_file}" "${header_file}"
        COMMAND "${EA_COMPILER}" "${source_abs}" --header
        WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}"
        DEPENDS "${source_abs}"
        COMMENT "Compiling Eä kernel: ${source}"
    )

    # Wrap the .o in a static library
    add_library(${target} STATIC "${obj_file}")
    set_target_properties(${target} PROPERTIES LINKER_LANGUAGE C)

    # Expose the generated header
    target_include_directories(${target} PUBLIC "${CMAKE_CURRENT_BINARY_DIR}")

    # Ensure the header is generated before anything that depends on this target
    add_custom_target(${target}_header DEPENDS "${header_file}")
    add_dependencies(${target} ${target}_header)
endfunction()
"#;
